templates/common/common.sh

Adds a placeholder `templates` subdir and further content that will be useful once Barbican is fleshed-out

Add placeholder templates dir

---

.github/workflows/build-barbican-operator.yaml

GitHub actions for builds mistakenly assume `master` is the default branch name and this results in images being pushed with incorrect `latest` tags

Fix build tags

---

api/v1beta1/common_types.go
api/v1beta1/zz_generated.deepcopy.go
config/samples/barbican_v1beta1_barbican.yaml

Currently the default values are ignored because these specs are set to 0 by webhook. Update the type from int32 to *int32 to avoid that behavior and ensure the expected default values are used.
This also removes the large replicas set in the sample config, because these are not suitable for testing.

Fix defaulting of Replicas spec

---

api/v1beta1/common_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicans.yaml
config/crd/bases/barbican.openstack.org_barbicanworkers.yaml

We use <Service Name>Password for service user passwords globally.

Fix inconsistent password selector value for service password

---

controllers/barbican_controller.go

This ensures the controller watches service account, role, and role bindings to reconcile these resources in case any change is made.

Watch RBAC resources to trigger reconcile

---

api/v1beta1/barbican_types.go
controllers/barbican_controller.go

This ensures the Ready Condition is reset when CR becomes once ready but something fails during reconfiguration.

Reset Ready condition when update failed

---

config/samples/kustomization.yaml

Two sample files were removed that are needed for the operator build to succeed [1] [2].  Without them this error is encountered:
```
$ IMAGE_TAG_BASE=quay.io/andrewbays/barbican-operator VERSION=0.0.1 IMG=$IMAGE_TAG_BASE:v$VERSION make manifests build docker-build docker-push bundle bundle-build bundle-push catalog-build catalog-push
...
Error: accumulating resources: 2 errors occurred:
* accumulateFile error: "accumulating resources from '../samples': '/home/ocp/podified/barbican-operator/config/samples' must resolve to a file"
* accumulateDirector error: "recursed accumulation of path '/home/ocp/podified/barbican-operator/config/samples': accumulating resources: 2 errors occurred:\n\t* accumulateFile error: \"accumulating resources from 'barbican_v1beta1_barbicanapi.yaml': evalsymlink …
```

Fix operator build

---

controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

This closes #39, by returning nil instead of err

Fix error on CR deletion

---

config/rbac/barbicankeystonelistener_editor_role.yaml
config/rbac/barbicankeystonelistener_viewer_role.yaml
config/rbac/role.yaml
controllers/barbican_controller.go

This patch adds the missing RBAC config for BarbicanWorker and BarbicanKeystoneListner that is causing the controller to get stuck in a crash loop.

Add missing RBAC config

---

config/rbac/role.yaml
controllers/barbican_controller.go

This patch adds a couple more RBAC annotations that are needed to get barbican-operator running.

Add more missing RBAC annotations

---

controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go
main.go

This automatically adds additional fields like reconcile_id etc.. from the controller context.
before :
`2023-05-18T01:53:14+03:00 INFO  controllers.KeystoneAPI Reconciled Service init successfully`
after:
`2023-05-18T02:00:28+03:00       INFO    Controllers.KeystoneAPI Reconciled Service init successfully    {"controller": "keystoneapi", "controllerGroup": "keystone.openstack.org", "controllerKind":"KeystoneAPI", "KeystoneAPI": {"name":"keystone","namespace":"openstack"}, "namespace": "openstack", "name": "keystone", "reconcileID": "512a4d9b-f31d-4fa4-a4cc-cd6c13e4455d"}
`
*by using per reconcile function respective logger objects, the intention is to lay the ground for parallel reconciliation in future and avoid race conditions as ctx objects are reconcile run specific.
*example logs …

switch to structured logging

---

api/v1beta1/common_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
config/crd/bases/barbican.openstack.org_barbicans.yaml
config/crd/bases/barbican.openstack.org_barbicanworkers.yaml

This patch removes the ContainerImage property from BarbicanTemplate to avoid a name collision with BarbicanComponentTemplate in components that inline both templates.

Remove duplicated ContainerImage

---

Makefile
api/bases/barbican.openstack.org_barbicanapis.yaml
api/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
api/bases/barbican.openstack.org_barbicans.yaml
api/bases/barbican.openstack.org_barbicanworkers.yaml

This is something that has changed in the Makefile since we started. Importantly, the functional tests in openstack-operator and possibly other places expect this to be there so that the crds can be loaded.

Add CRDs under api

---

controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

This fixes the conditions for the various `Barbican*` CRDs such that the top-level `Barbican` CR can reach the "ready" state.  By fixing this, we also allow Barbican to properly integrate with the OpenStack operator, as the latter operator relies on the `Barbican` CR reaching the ready state in order for its own `OpenStackControlPlane` CR to reach the ready state.

Properly set certain conditions to True when necessary

---

.prow_ci.env
Makefile
api/v1beta1/barbican_types.go
config/default/manager_default_images.yaml
config/manager/kustomization.yaml
config/manifests/bases/barbican-operator.clusterserviceversion.yaml

This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.
For Prow jobs we are enabling this via .prow-ci.env
(NOTE: this currently requires a secure registry)

Support disconnected network environments

---

config/rbac/role.yaml
controllers/barbican_controller.go

This is needed in case the the user includes any `networkAttachments` in the various CRs.  Otherwise we see this:
```
E1218 13:13:53.990846       1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.9/tools/cache/reflector.go:169: Failed to watch *v1.NetworkAttachmentDefinition: failed to list *v1.NetworkAttachmentDefinition: network-attachment-definitions.k8s.cni.cncf.io is forbidden: User "system:serviceaccount:openstack-operators:barbican-operator-controller-manager" cannot list resource "network-attachment-definitions" in API group "k8s.cni.cncf.io" at the cluster scope
```

Add missing net-attach-def permissions

---

api/bases/barbican.openstack.org_barbicanapis.yaml
api/bases/barbican.openstack.org_barbicans.yaml
api/v1beta1/barbicanapi_types.go
api/v1beta1/common_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicans.yaml
controllers/barbican_controller.go
controllers/barbicanapi_controller.go
templates/barbican/config/00-default.conf

This patch adds a new field to the BarbicanAPI spec to configure "Consistent and Secure RBAC" [1].  The API configuration template was modified to use the value in this field instead of being hard-coded to always be on.
Jira: OSPRH-2129
[1] https://governance.openstack.org/tc/goals/selected/consistent-and-secure-rbac.html

Make Secure RBAC configurable

---

templates/barbican/config/00-default.conf

Without this, `Barbican` deployment fails with...
```
- lastTransitionTime: "2024-01-02T17:33:48Z"
message: 'Service config create error occurred template: tmp:31:19: executing
"tmp" at <.EnableSecureRBAC>: map has no entry for key "EnableSecureRBAC"'
reason: Error
severity: Warning
status: "False"
type: Ready
```
...for certain sub-types (worker, Keystone listener, etc) that do not set the value in their respective reconcile loop.

Fix 'EnableSecureRBAC' templating

---

Makefile

specify version for operator-sdk for make bundle
download operator-sdk pinned version when generating bundle update make bundle to use local operator-sdk
update to 1.31 version

update for local operator-sdk

---

.ci-operator.yaml

This config file is used by Prow to define the base image for jobs. It is a config per project.

Add ci-operator base image config for Prow jobs

---

controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go
pkg/barbican/const.go

During the test of `Glance` image sign that rely on `Barbican` to store secrets, we’d see `Connection refused` errors on about 60% of the calls made to the service. This let the image signing fail most of the times.
In addition, simply running `curl` against the `barbican-internal` endpoint shows this issue, because it fails more than **half** of the times with a `connection refused` error on 9311.
However, if we point directly to the `Pod` (bypassing the k8s `Service`), we can see that this problem doesn't occur, and we're able to always reach the `Barbican` service and successfully sign the `Glance` images.
The root cause of this issue is the k8s `Service` sending traffic to the `BarbicanAPI`, as well as `keystoneListener` and `BarbicanWorker`: these two services are not listening on …

Fix intermittent connection refused

---

pkg/barbicanapi/deployment.go
pkg/barbicankeystonelistener/deployment.go
pkg/barbicanworker/deployment.go

As noticed in other operators (and already fixed), the -log sidecar ignores `SIGTERM` on delete.
This patch moves the barbican-operator to the `dumb-init` usage to make sure the `SIGTERM` is handled properly by the sidecar.
Fixes: [OSPRH-3283](https://issues.redhat.com/browse/OSPRH-3283)

Move -log sidecar container to dumb-init

---

controllers/barbicanapi_controller.go
controllers/barbicanworker_controller.go
templates/barbican/config/00-default.conf

This patch changes the configuration template to use a KEK provided in the OSP secret instead of a hard-coded one.

Use Simple Crypto KEK from Secret

---

kuttl-test.yaml

Small trailing whitespace that is failing on
pre-commit tests. Needs fix before adding pre-commit job in [1]
[1] https://github.com/openshift/release/pull/48117

Small fix for pre-commit test

---

.prow_ci.env
Dockerfile
Makefile

- Changed the build image to ubi9/go-toolkit
- Changed the base image to ubi9/minimal
- Added the default GO_BUILD_EXTRA_ARGS="-tags strictfipsruntime"
- Added the GO_BUILD_EXTRA_ENV_ARGS build argument to allow custom build arguments at build time. It defaults to "CGO_ENABLED=1 GO111MODULE=on"
- Those default parameters have been added to enable FIPS compliance
- Fixed indentation
- Removed TARGETOS and TARGETARCH env vars.
- Added DOCKER_BUILD_ARGS variable in Makefile to pass custom parameters during podman build
- Added export FAIL_FIPS_CHECK=true in .prow_ci.env file

FIPS compliant images

---

config/rbac/role.yaml
controllers/barbican_controller.go
go.mod
go.sum
tests/functional/barbican_controller_test.go

This change bumps the mariadb-operator version and makes the necessary changes to work with the updated version.

Bump mariadb-operator version

---

api/bases/barbican.openstack.org_barbicanapis.yaml
api/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
api/bases/barbican.openstack.org_barbicans.yaml
api/bases/barbican.openstack.org_barbicanworkers.yaml
api/v1beta1/common_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
config/crd/bases/barbican.openstack.org_barbicans.yaml
config/crd/bases/barbican.openstack.org_barbicanworkers.yaml
config/samples/barbican_v1beta1_barbican.yaml
controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicanworker_controller.go
tests/functional/barbican_controller_test.go
tests/functional/base_test.go

This patch adds the ability to separate the Key Encryption Key (KEK) used by the Simple Crypto backend from the general purpose osp-secret used with the rest of openstack.
By default we still use osp-secret, but the barbican spec can now be configured to use a separate secret as well as a custom key for retrieving the value from the secret.
Jira: [OSPRH-2390](https://issues.redhat.com//browse/OSPRH-2390)

Add options to separate KEK from osp-secret

---

controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go
pkg/barbican/volumes.go
tests/functional/barbican_controller_test.go
tests/kuttl/tests/barbican_tls/01-assert.yaml

The my.cnf file gets added to the secret holding the service configs. The content of my.cnf is centrally managed in the mariadb-operator and retrieved calling db.GetDatabaseClientConfig(tlsCfg)
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/190
Depends-On: https://github.com/openstack-k8s-operators/mariadb-operator/pull/191
Jira: [OSPRH-4547](https://issues.redhat.com//browse/OSPRH-4547)

[tlse] TLS database connection

---

Makefile
api/bases/barbican.openstack.org_barbicanapis.yaml
api/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
api/bases/barbican.openstack.org_barbicans.yaml
api/bases/barbican.openstack.org_barbicanworkers.yaml
api/go.mod
api/go.sum
api/v1beta1/common_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
config/crd/bases/barbican.openstack.org_barbicans.yaml
config/crd/bases/barbican.openstack.org_barbicanworkers.yaml
config/samples/barbican_v1beta1_barbican.yaml
controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go
go.mod
go.sum
pkg/barbican/const.go
tests/functional/barbican_controller_test.go
tests/functional/barbican_test_data.go
tests/kuttl/common/assert_sample_deployment.yaml
tests/kuttl/tests/barbican_tls/01-assert.yaml

…BAccountLead Jira: [OSPRH-4095](https://issues.redhat.com/browse/OSPRH-4095)
1. [x] controller calls EnsureMariaDBAccount up front to make sure MariaDBAccount is present
2. [x] error code from EnsureMariaDBAccount is handled, Conditions are amended when error is returned
3. [x] controller calls NewDatabaseForAccount instead of NewDatabase
4. [x]  GetAccountAndSecret is used to retrieve account /secret to populate template
5. [x]  GetDatabaseByName() , normally used for delete finalizers, replaced with GetDatabaseByNameAndAccount
6. [x]  CreateOrPatchAll() used to patch the Database, replacing CreateOrPatchDB / CreateOrPatchDBByName
7. [x]  controller calls DeleteUnusedMariaDBAccountFinalizers when launched pods are definitely running on a new MariaDBAccount, returns error code if present …

migrate from databaseUsername to databaseAccount and fully use MariaDBAccount

---

Makefile

https://github.com/kubernetes-sigs/controller-runtime/pull/2693 broke
the functional tests running downstream with following issue[1]
In order to unblock the CI, we are pinning
sigs.k8s.io/controller-runtime/tools/setup-envtest at previous working commit[2]
Links:
[1]. https://github.com/kubernetes-sigs/controller-runtime/issues/2720 [2]. https://github.com/kubernetes-sigs/controller-runtime/commit/c7e1dc9b5302d649d5531e19168dd7ea0013736d

Pin setup-envtest at working commit to fix functional tests

---

Makefile

kubernetes-sigs/controller-runtime#2693 broke the content provider while doing docker-build with following issue[1]
In order to unblock the CI, we are pinning
sigs.k8s.io/controller-runtime/tools/setup-envtest at previous working commit[2]
[1]. kubernetes-sigs/controller-runtime#2720
[2]. kubernetes-sigs/controller-runtime@c7e1dc9

Pin setup-envtest to c7e1dc9

---

api/go.mod
api/go.sum
api/v1beta1/barbican_webhook.go
go.mod
go.sum
tests/functional/barbican_controller_test.go

Depends-On: https://github.com/openstack-k8s-operators/lib-common/pull/505

Check for valid service override endpoint type on create and update

---

config/manifests/bases/barbican-operator.clusterserviceversion.yaml

This removes the operators.openshift.io/infrastructure-features annotation which has been deprecated [0].
[0]: https://github.com/openstack-k8s-operators/barbican-operator/pull/130#discussion_r1657438125

Remove deprecated annotation

---

config/rbac/role.yaml
controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

We also took the opportunity and added patch to all the existing rbac rules that had update already to avoid similar issues in the future
Resolves: https://issues.redhat.com/browse/OSPRH-8363

Adding patch rbac perm for serviceaccounts

---

controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

Currently the reconciler returned both a non-zero result and a non-nil error.
The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff.
In case of NotFound return nil that the ReqeueAfter is used.
For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler

Return nil error in case NotFound and to use RequeueAfter

---

api/go.mod
api/go.sum
controllers/barbicanapi_controller.go
go.mod
go.sum

We've come to realize three things recently:
1. Returning an error to the reconciler along with a `RequeueAfter` will cause the reconciler to abandon the explicit requeue and only consider the error [1].
2. The `VerifySecret` function in `lib-common` was returning an error along with a requeue, thus contributing to the problem listed in item 1. [2]
3. Also, the error `VerifySecret` was returning was _not_ a "not found" error, but a generic k8s error -- so it wouldn't be properly handled by callers looking for a "not found" error. [3]
Now `VerifySecret` only returns a non-empty `ctrl.Result{}` if the `Secret` is missing, so let's handle that case in a separate if-clause. [4]
Jira: https://issues.redhat.com/browse/OSPRH-9371
[1] https://github.com/openstack-k8s-operators/keystone-operator/pu …

[OSPRH-9371] Fix VerifySecret so it requeues when necessary

---

controllers/barbican_controller.go
pkg/barbicanapi/deployment.go
pkg/barbicankeystonelistener/deployment.go
pkg/barbicanworker/deployment.go
tests/kuttl/tests/barbican_scale/02-assert.yaml
tests/kuttl/tests/barbican_scale/03-assert.yaml

The previous Barbican operator's code was not taking actions when the `nodeSelector` attribute was specified in the control plane. This patch addresses the missing part.

Adding nodeSelector functionality

---

config/samples/barbican_v1beta1_barbican.yaml
config/samples/tls-e/barbican_v1beta1_barbican.yaml

When other services deploy barbican as a dependency in CI using the barbican sample the nodeselector functionality, which was added recently with
https://github.com/openstack-k8s-operators/barbican-operator/pull/153 prevents the pods from being able to be scheduled. Therefore this change will comment these optional settings.

[sample] comment optional nodeSelector

---

controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

This PR is a continuation of [PR #145](https://github.com/openstack-k8s-operators/barbican-operator/pull/145).  Barbican Keystone Listener and Barbican Worker were missed being fixed.

Continuation pr145

---

controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

It is hidden right now if there is an error in configured named fields and index. Lets log the error and return the current state of requests.
With this the findObjectsForSrc() will exit with an hidden error like:
```
"error": "Index with name field:.spec.ksmTls.caBundleSecretName does not exist"
```

Make sure to log error in findObjectsForSrc()

---

api/bases/barbican.openstack.org_barbicanapis.yaml
api/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
api/bases/barbican.openstack.org_barbicanworkers.yaml
api/v1beta1/common_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicankeystonelisteners.yaml
config/crd/bases/barbican.openstack.org_barbicanworkers.yaml
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go
pkg/barbican/const.go
templates/barbican/config/barbican-api-config.json
templates/barbican/config/barbican-keystone-listener-config.json
templates/barbican/config/barbican-worker-config.json

This PR adds support for the `CustomServiceConfig` field in the Barbican CRD, allowing custom configurations for the Barbican API, worker, and keystone-listener services.
Example:
```yaml
barbican:
template:
databaseInstance: openstack
secret: osp-secret
barbicanAPI:
customServiceConfig: |
[DEFAULT]
max_allowed_secret_in_bytes = 1048576
replicas: 1
```
The custom config file is now mounted as a  `02-service-custom.conf` file to `/var/lib/config-data/default/`  location and copied to `/etc/barbican/barbican.conf.d/` as a `custom.conf` file.

Fix CustomServiceConfig barbican configuration

---

api/v1beta1/barbican_types.go
api/v1beta1/common_types.go
api/v1beta1/zz_generated.deepcopy.go
controllers/barbican_controller.go
pkg/barbican/dbsync.go
pkg/barbicanapi/deployment.go
pkg/barbicankeystonelistener/deployment.go
pkg/barbicanworker/deployment.go
tests/functional/barbican_controller_test.go

nodeSelectors are not currently applied consistently across all operators.
Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.
Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

Ensure nodeSelector logic is consistent for all operators

---

controllers/barbican_common.go
hack/crd-schema-checker.sh

Putting back the CRD Schema Validator tool.

Reenabling CRD Schema Validator

---

api/bases/barbican.openstack.org_barbicanapis.yaml
api/bases/barbican.openstack.org_barbicans.yaml
api/v1beta1/barbican_types.go
api/v1beta1/barbican_webhook.go
api/v1beta1/barbicanapi_types.go
config/crd/bases/barbican.openstack.org_barbicanapis.yaml
config/crd/bases/barbican.openstack.org_barbicans.yaml
controllers/barbican_controller.go
controllers/barbicanapi_controller.go
templates/barbican/config/10-barbican_wsgi_main.conf
tests/functional/barbican_controller_test.go
tests/functional/barbican_test_data.go

...to allow configure timeouts for HAProxy and Apache.
Jira: https://issues.redhat.com/browse/OSPRH-10964

Add configurable API Timeout

---

tests/functional/barbican_controller_test.go
tests/functional/barbican_test_data.go
tests/functional/base_test.go
tests/functional/suite_test.go

Functional tests for the Luna HSM model support.

Functional tests for HSM Support

---

api/v1beta1/barbican_webhook.go

Update SetDefaultRouteAnnotations(..) to use *BarbicanSpecCore instead of *BarbicanAPITemplateCore to correctly reference the timeout setting.
Previously, the webhook in openstack-operator was incorrectly using the BarbicanAPI timeout (set to 0), instead of the Barbican timeout, which takes precedence. This caused the route timeout to be set incorrectly.
In openstack-operator we can then use: `r.Spec.Barbican.Template.SetDefaultRouteAnnotations(r.Spec.Barbican.APIOverride.Route.Annotations)`
instead of:
`r.Spec.Barbican.Template.BarbicanAPI.SetDefaultRouteAnnotations(r.Spec.Barbican.APIOverride.Route.Annotations)`
Which was referencing incorrect timeout.
Jira: https://issues.redhat.com/browse/OSPRH-10964

Update the route timeout webhook reference

---

api/v1beta1/barbican_webhook.go

Handle cases where the user sets ApiTimeout to 0 by resetting it to the default value. 
Fixed annotation typo `"api.Barbican.openstack.org/timeout" ` --> `"api.barbican.openstack.org/timeout"` Annotations should be lowercase

Fix ApiTimeout reset to default and correct annotation case typo

---

templates/barbican/bin/generate_pkcs11_keys.sh

Right now, generate_pkcs11_keys.sh will read from the config and take the value of the mkek and hmac labels as-is, without removing any quotes.  So, if the config file has quotes around the value, like "foo", the key "foo" (with quotes) will be created.
Of course, when barbican-api comes up, it strips the quotes and starts looking for key foo(and cannot find it).
This fixes the problem by stripping quotes from the value in the script.

Fix generate_pkcs11_keys.sh to handle quotes

---

api/bases/barbican.openstack.org_barbicans.yaml
api/v1beta1/barbican_types.go
config/crd/bases/barbican.openstack.org_barbicans.yaml

...to prevent user from setting a negative value. Minimum value of 10 follows common implementation in other operators.

Set APITimeout minimum validation

---

pkg/barbican/const.go
pkg/barbican/dbsync.go
pkg/barbican/funcs.go
pkg/barbican/volumes.go
pkg/barbicanapi/deployment.go
pkg/barbicankeystonelistener/deployment.go
pkg/barbicanworker/deployment.go
templates/barbican/config/barbican-api-config.json
tests/kuttl/tests/barbican_tls/01-assert.yaml

As done for several service operators, this patch removes root from the `Barbican` services.
`SecurityContexts` are created to address requirements related to different services.
Jira: https://issues.redhat.com/browse/OSPRH-15340

Run Barbican services without root

---

kuttl-test.yaml
zuul.d/jobs.yaml
zuul.d/projects.yaml

Add KUTTL and tempest zuul jobs (meant to replace/complement the prow ones in the long term)
KUTTL: generate JUnitXML reports
- switch the type to XML (the accepted value is 'xml' lowercase, not uppercase);
- tune the name a bit to highlight it is a report;
- add the new reportGranularity parameter which is supported by kuttl 0.20.0 and will restore the pre-1.17 JUnitXML format (granularity by test case, instead of by step).
- remove the URL of kuttl, so that it is not tied to a specific release.

 More zuul jobs, and generate JUnitXML reports for KUTTL

---

controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

Currently we use deferred call to always update the status field when Reconcile call exits, which seems correct for any other error except when Reconciler exits due to panic.
This change adds a call to recover function and try to handle panic and log error.
Closes: [OSPRH-16971](https://issues.redhat.com//browse/OSPRH-16971)

Do not update status when reconciler exits due to panic

---

controllers/barbican_controller.go
go.mod
go.sum
tests/functional/barbican_controller_test.go

Adds watches of the Nova controller on the KeystoneAPI status to reconcile if e.g. the endpoint list changes. This triggers setting the new KeystoneAuthURL on the sub components to update their configuration.
Depends-On: https://github.com/openstack-k8s-operators/keystone-operator/pull/591
Jira: [OSPRH-16994](https://issues.redhat.com//browse/OSPRH-16994)

Watch KeystoneAPI status updates to reconcile

---

controllers/barbican_controller.go
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go

This change uses GetLogger instead of direct use of log.FromContext to support structured logging.

Use structured logging

---

api/v1beta1/webhook_suite_test.go
config/certmanager/certificate.yaml
controllers/barbicanapi_controller.go
controllers/barbicankeystonelistener_controller.go
controllers/barbicanworker_controller.go
kuttl-test.yaml
tests/functional/suite_test.go

- Replace deprecated Kubernetes user-guide URLs with current documentation paths
- Update Ginkgo documentation links from HTTP to HTTPS
- Fix cert-manager upgrade documentation path from /upgrading/ to /upgrade/
Fixes 404 errors and ensures all documentation links point to current, valid URLs.
Assisted-by: claude-4-sonnet

fix: update broken and outdated documentation URLs
